<?php
	session_start();
    $_item = $this->getItem();
	$themeOptions = $this->helper('idstore');
    $enableAjax = $themeOptions->ajaxIsEnabled();
    $isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
    $canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>
<li class="item">
    <?php if ($this->hasProductUrl()): ?>
        <a title="<?php echo $this->htmlEscape($this->getProductName()) ?>" class="product-image"><img src="<?php echo $this->getProductThumbnail()->resize(75, 100)->setWatermarkSize('30x10'); ?>" width="75" height="100" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" /></a>
    <?php else: ?>
        <span class="product-image"><img src="<?php echo $this->getProductThumbnail()->resize(75, 100)->setWatermarkSize('30x10'); ?>" width="75" height="100" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" /></span>
    <?php endif; ?>
    <div class="product-details">
        <button id="<?php echo $_item->getProductId() ?>" addurl="<?php $ids = $_item->getProductId(); echo $_SESSION['qty'.$ids]; ?>" remurl="<?php $ids = $_item->getProductId(); echo $_SESSION['qtyr'.$ids]; ?>" onclick="eightTheme.ajaxRemove('<?php echo $this->getDeleteUrl() ?>', true);refresh(<?php echo $_item->getProductId()?>);"><span>remove</span></button>
        <div class="item_price">
        <strong><?php echo $this->getQty() ?> x</strong>

        <?php if ($canApplyMsrp): ?>

            <span class="map-cart-sidebar-item"><?php echo $this->__('See price before order confirmation.'); ?></span>

        <?php else: ?>

        <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <?php echo $this->__('Excl. Tax'); ?>:
            <?php endif; ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
                <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
            <?php else: ?>
                <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
            <?php endif; ?>
            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <br />
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php endif; ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
            <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <br /><?php echo $this->__('Incl. Tax'); ?>:
            <?php endif; ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
                <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?>
            <?php else: ?>
                <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
            <?php endif; ?>
            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <br />
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php endif; ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?></span>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>

        <?php endif; //Can apply MSRP ?>
    </div>
        <div class="bord_right">
        <p class="product-name"><?php if ($this->hasProductUrl()): ?><a><?php endif; ?><?php echo $this->htmlEscape($this->getProductName()) ?><?php if ($this->hasProductUrl()): ?></a><?php endif; ?>


<!-- Cabooza.com CB-9-PHTML -->

<div class="item-info">
 <?php
    $product_ob = Mage::getModel('catalog/product')->load($_item->getProductId());
    echo $product_ob->getShortDescription();
?>
</div>
</div>

</p>
    
        <?php if ($_options = $this->getOptionList()):?>
        <div class="truncated">
          <div class="truncated_full_value">
            <dl class="item-options">
                <?php foreach ($_options as $_option) : ?>
                <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
                <dd>
                    <?php if (is_array($_option['value'])): ?>
                    <?php echo nl2br(implode("\n", $_option['value'])) ?>
                    <?php else: ?>
                    <?php echo $_option['value'] ?>
                    <?php endif; ?>
                </dd>
                <?php endforeach; ?>
            </dl>
          </div>
        <a href="#" onclick="return false;" class="details"><?php echo $this->__('Details') ?></a>
        </div>
        <?php endif; ?>
		
		
    </div>
	
<div class="clear"></div>

<div class="item-options">
	<label><?php echo $this->__('in case product not available:') ?></label>
	
		<select prodId="<?php echo $_item->getProductId() ?>" id="<?php echo 'id'.$_item->getProductId() ?>">
		
			<option value="1"><?php echo $this->__('Replace with a similar one') ?></option>
			<option value="2"><?php echo $this->__('Waiver of this purchase') ?></option>
		</select>
</div>	
	
</li>
<div>

<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery("#cart-sidebar select").change(function(){
	     var prodId1 = jQuery(this).attr('prodid');
		if(jQuery(this).val() != "0")
		{
			var value1 = jQuery(this).val();
			var data1 = { id: prodId1, value: value1 };
			
			jQuery.ajax({
			  type: "POST",
			  cache: false,
			  url: "http://cabooza.com/updatesession.php",
			  data: data1,
			  success: function(d){
			  
			  },
			  error: function (d){
			  
			  }
			  
			});
			/* .done(function( msg ) {
				jQuery('.search_text').text(msg);
			}) */
		}
	});
	var prodId1 = <?php echo $_item->getProductId() ?>;
	var data1 = { id: prodId1, value: "3" };
	jQuery.ajax({
			  type: "POST",
			  cache: false,
			  url: "http://cabooza.com/updatesession.php",
			  data: data1,
			  success: function(d){
				jQuery('<?php echo '#cart-sidebar #id'.$_item->getProductId() ?>').eq(1).val(d);
			  },
			  error: function (d){
			  }
	});
	
});

</script>
</div>
<script>

</script>