<!-- Finding Current Category and Finding it's children -->

<?php


    $_helper = $this->helper('catalog/output');
        
    $themeOptions = $this->helper('idstore');
    $enableAjax = $themeOptions->ajaxIsEnabled();
    $cols = $themeOptions->gridColumnCount();
    $template = $this->getLayout()->getBlock('root')->getTemplate();
    
    $catHelper = $this->helper('idstore/category');
    $catHelper->setOptions($cols, $template);
    $isHoverswapEnabled = $themeOptions->useHoverSwap();
    $imgW1 = $catHelper->getImgWidth();
    $imgH1 = $catHelper->getImgHeight();
    $span_class = $catHelper->getSpanClass();
    $imgW = 540;
    $imgH = 740;
	
	
$category = Mage::getSingleton('catalog/layer')->getCurrentCategory();
$categories = $category->getCollection()
        ->addAttributeToSelect(array('name', 'thumbnail'))
        ->addAttributeToFilter('is_active', 1)
        ->addIdFilter($category->getChildren())
?>

<div class="subcategories">
  <h2 style=" background: #cee3c9 none repeat scroll 0 0;color: #fff;font-size:24px;padding: 24px 10px;"><?php echo $category->getName(); ?></h2>
  <div class="clearfix"> 
    <!-- Display Each Subcategory Image and Name  -->
    
    <?php foreach ($categories as $category): ?>
    <div style="clear:both;" ></div>
    <h3 style="margin-top: 20px; float:left;"> <a href="<?php echo $category->getUrl() ?>" class="clearfix">
      <?php if($thumbFile = $category->getThumbnail()): ?>
      <img src="<?php echo Mage::getBaseUrl('media') . 'catalog' . DS . 'category' . DS . $thumbFile;?>" alt="<?php echo $this->htmlEscape($category->getName()) ?>" />
      <?php endif;?>
      <span style="font-size:20px; margin-left:10px;"><?php echo $category->getName() ?></span></a>  
      </h3>
      <a href="<?php echo $category->getUrl() ?>" class="cat-viewmore" style="background: #eef5ec none repeat scroll 0 0;border: 1px solid #5aa249;border-radius: 5px;color: #5aa249;display: block;float: left;margin-left: 40px;margin-top: 17px; padding: 3px 10px;">Mostra altri &gt;</a>
    <div style="clear:both;" ></div>
    <!-- Load (3) Products from within each subcategory  -->
    <?php
        $_helper = $this->helper('catalog/output');
        $products = Mage::getModel('catalog/product')
            ->getCollection()
            ->addCategoryFilter($category)
			->addAttributeToFilter('status', array('eq' => Mage_Catalog_Model_Product_Status::STATUS_ENABLED))
			
            ->setPageSize(6)
            ->addAttributeToSelect(array('name', 'product_url', 'small_image'));
            Mage::getSingleton('cataloginventory/stock')->addInStockFilterToCollection($products);
			$products->load();
				//Mage::getSingleton('cataloginventory/stock')->addInStockFilterToCollection($this->_productCollection)
        ?>
        <!--
    <div class="products_grid row rows-count6"> 
     
      
	  
	  
	  <?php /*foreach ($products as $product): ?>
     	 	<div class="product-grid span3 last">
      			<a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>" class="product-image new-bg">
        		<div class="img-wrapper"></div>
        		<div class="img-wrapper hideableHover" > 
                	<img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->keepFrame(true)->resize($imgW, $imgH) ?>" width="<?php echo $imgW ?>" height="<?php echo $imgH ?>" alt="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>" /> 
                </div>
        		</a>
        		<?php $_productNameStripped = $this->stripTags($product->getName(), null, true); ?>
        			<div class="product-information">
          				<h2 class="product-name">
                        	<a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $productNameStripped; ?>">
								<?php echo $_helper->productAttribute($product, $product->getName() , 'name'); ?>
                            </a>
                         </h2>
        			</div>
      		</div>
      <?php endforeach ; */?>
      
      
      
      
      
    </div>-->
    
    	<div class="category-products" style="margin-bottom:30px;">
			
                
                <?php $_columnCount = count($products); ?>
              
                <div class="products_grid row rows-count6">
                
                    <?php $i=0; foreach ($products as $_product): ?>
                      <?php $prcus = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                        <?php /*?><div class="product-grid  <?php echo $span_class ?>	<?php if (($i-1)%$_columnCount==0): ?> first<?php elseif ($i%$_columnCount==0): ?> last<?php endif; ?> meet"><?php */?>
                        <div class="product-grid span2 last">
                        
        
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
                                <?php echo $this->getLayout()->createBlock('idstore/product_ribbons')->setTemplate('catalog/product/view/ribbons.phtml')->setData('product', $_product)->toHtml(); ?>
                                <?php if ($isHoverswapEnabled): ?>
                                <div class="img-wrapper">
									<?php echo $this->getLayout()->createBlock('idstore/product_hoverswap')->setTemplate('catalog/product/view/hoverswap.phtml')->setData('product', $_product)->setData('width', $imgW)->setData('height', $imgH)->toHtml(); ?></div>
                                <?php endif ?>
                                <div class="img-wrapper<?php if ($isHoverswapEnabled) echo ' hideableHover' ?>"><img class="product_image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(true)->resize($imgW, $imgH) ?>" width="<?php echo $imgW ?>" height="<?php echo $imgH ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                                </div>
                            </a>
                            <div class="product-information">
                            
                                <h2 class="product-name">
                                	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
										<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>
                                </h2>
                                <!-- Cabooza.com CB-6-PHTML -->
								<?php 
									// echo '<pre>';
									// print_r($_product->toArray());
									// exit;
									
								?>
								<h6 class="meet2"><?php echo $prcus->getShortDescription(); ?></h6>
        
                                <?php if ($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                <?php endif; ?>
                                
                                <div id="productname<?php echo $_product->getId() ?>" style="display:none"><?php echo $this->stripTags($_product->getName(), null, true) ?></div>
                                
                                <?php //echo $this->getPriceHtml($_product, true) ?>
								<?php 
										
									echo Mage_Catalog_Block_Product::getPriceHtml($prcus, true);  
									
								?>
                                
                                <ul class="add-to-links<?php if (!$themeOptions->useAddtoButtons()) echo ' hidden'?>">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if ($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                    <?php endif; ?>
                                </ul>
                                <div class="clear"></div>
                            </div>
                            
                            <?php
                            $idthisproduct = $_product->getId();
                            ?>
                            <div class="prodid"><?php echo $idthisproduct;?></div>
                            <?php
                            $numberincart=0;
                            $cart = Mage::getModel('checkout/cart')->getQuote();
                            foreach ($cart->getAllItems() as $item) {
                                $idcartproduct = $item->getProduct()->getId();
                                if($idcartproduct == $idthisproduct){
                                    $numberincart = $item->getQty();
                                }
                            }
                            
							//Mage::helper('checkout/cart')->getAddUrl($_product)
							
                            ?>
                            <div id="<?php echo 'adt'.$idthisproduct;?>" class="adt" style="display:none;">
                                <div class="qty"></div>
                                <button id="<?php echo 'qtyr'.$idthisproduct; $_SESSION['qty'.$idthisproduct] = 'eightTheme.ajaxAddProduct(\''.Mage::helper('checkout/cart')->getAddUrl($_product).'\',\''.$_product->getId().'\');addp('.$idthisproduct.');';$_SESSION['qtyr'.$idthisproduct] = 'eightTheme.ajaxRemoveOne(\''.Mage::helper('checkout/cart')->getAddUrl($_product).'\',\''.$_product->getId().'\');remp('.$idthisproduct.');';?>" onclick="eightTheme.ajaxRemoveOne('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>','<?php echo $_product->getId()?>');remp(<?php echo $idthisproduct;?>);" class="del"></button>

                                <button id="<?php echo 'qtyr'.$idthisproduct; $_SESSION['qty'.$idthisproduct] = 'eightTheme.ajaxAddProduct(\''.Mage::helper('checkout/cart')->getAddUrl($_product).'\',\''.$_product->getId().'\');addp('.$idthisproduct.');';$_SESSION['qtyr'.$idthisproduct] = 'eightTheme.ajaxRemoveOne(\''.Mage::helper('checkout/cart')->getAddUrl($_product).'\',\''.$_product->getId().'\');remp('.$idthisproduct.');';?>" onclick="eightTheme.ajaxAddProduct('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>','<?php echo $_product->getId()?>');addp(<?php echo $idthisproduct;?>);" class="add"></button>
                                
                            </div> 
                            
                            
                            <div class="actions btn-cont" onclick="eightTheme.ajaxAddProduct('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product); ?>','<?php echo $_product->getId()?>');addp(<?php echo $idthisproduct;?>);">  
                                <?php if ($_product->isSaleable()): ?>
                                    <?php if ( !($_product->getTypeInstance(true)->hasOptions($_product) || $_product->isGrouped()) ): ?>
                                    
                                    <?php else: ?>
                                    <button type="button" title="<?php echo $this->__('+') ?>" class="button btn-cart" onclick="eightTheme.ajaxShowOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('+') ?></span></span></button>
                                    <a href='<?php echo $this->getUrl('e_ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style="display: none;" ><?php echo $this->__('+') ?></a>
                                    <?php endif ?>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                            </div>
                            <?php
                                if($numberincart > 0){
                                    ?>
                                    <script>
                                        var element="<?php echo '#adt'.$idthisproduct; ?>";
                                        jQuery(element).show();
                                        jQuery(element).next().css('display','block');
                                        jQuery(element).find('.qty').text(<?php echo $numberincart;?>);
                                    </script>
                                    <?php
                                }
                            ?>
                            <div id="productimgover<?php echo $_product->getId()?>" style="display: none;"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(75); ?>" width="64" height="64" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></div>
                            <div id='productname<?php echo $_product->getId()?>' style='display:none'><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></div>
                            
                        </div>
                        
                    <?php endforeach ?>
                    
                </div>
                
                <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
                    
            
        </div>
    
    <?php endforeach; ?>
  </div>
</div>
<style type="text/css">
.new-bg{
	background:#FFF;
	min-height:240px;
	}
	.product-grid .price-box { float:none !important;}
</style>
