<?php $themeOptions = $this->helper('idstore'); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1><?php echo Mage::helper('contacts')->__('Contact Us') ?></h1>
</div>

<div id="map" class="google-map">
    <p>Enable your JavaScript!</p>
</div>	

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
    
    function etheme_google_map() {
        var styles = {
            '8theme':  [{
            "featureType": "administrative",
            "stylers": [
              { "visibility": "on" }
            ]
          },
          {
            "featureType": "road",
            "stylers": [
              { "visibility": "on" },
              { "hue": "#e78b8b" }
            ]
          },
          {
            "stylers": [
			  { "visibility": "on" },
			  { "hue": "#e78b8b" },
			  { "saturation": -50 }
            ]
          }
        ]};
        
        var myLatlng = new google.maps.LatLng(<?php echo $themeOptions->googleMap(); ?>);
        var myOptions = {
            zoom: 17,
            center: myLatlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            disableDefaultUI: true,
            mapTypeId: '8theme',
            draggable: true,
            zoomControl: true,
			panControl: false,
			mapTypeControl: true,
			scaleControl: true,
			streetViewControl: true,
			overviewMapControl: true,
            scrollwheel: false,
            disableDoubleClickZoom: false
        }
        var map = new google.maps.Map(document.getElementById("map"), myOptions);
        var styledMapType = new google.maps.StyledMapType(styles['8theme'], {name: '8theme'});
        map.mapTypes.set('8theme', styledMapType);
        
        var marker = new google.maps.Marker({
            position: myLatlng, 
            map: map,
            title:""
        });   
    }
    jQuery(document).ready(function(){
	    etheme_google_map();
    });
    
    jQuery(document).resize(function(){
	    etheme_google_map();
    });
</script>

<div class="row-fluid">
	<div class="span7">
		<form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">
		    <div class="fieldset">
		        <h2 class="legend"><?php echo Mage::helper('contacts')->__('Contact Information') ?></h2>
		        <ul class="form-list">
		            <li class="fields">
		                <div class="field">
		                    <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
		                    <div class="input-box">
		                        <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
		                    </div>
		                </div>
		                <div class="field">
		                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
		                    <div class="input-box">
		                        <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
		                    </div>
		                </div>
		                <div class="field">
			                <label for="telephone"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
			                <div class="input-box">
			                    <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text" type="text" />
			                </div>
		                </div>
		            </li>
		            <li class="wide">
		                <label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>
		                <div class="input-box">
		                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
		                </div>
		            </li>
		        </ul>
		    </div>
		    <div class="buttons-set">
		        <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
		        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
		        <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
		    </div>
		</form>
		<script type="text/javascript">
		//<![CDATA[
		    var contactForm = new VarienForm('contactForm', true);
		//]]>
		</script>
	</div>
	<div class="span5 contacts-info"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contacts_block')->toHtml(); ?></div>	
</div>