<div style="background: #fafafa;">				
				<!-- START REVOLUTION SLIDER 2.3.91 -->
				
								
								<div id="rev_slider_2_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" style="margin:0px auto;background-color:#ffffff;padding:0px;margin-top:0px;margin-bottom:20px;max-height:480px;">
					<div id="rev_slider_2_1" class="rev_slider fullwidthabanner" style="display:none;max-height:480px;height:480;">						
										<ul>
								<li data-transition="slidehorizontal" data-slotamount="7" data-masterspeed="300" data-delay="8000" >
						<img src="http://8theme.com/dev/new/wp-content/uploads/2013/05/slider_034.jpg"  alt="slider_034" data-fullwidthcentering="on">
														
				<div class="tp-caption main-caption lfl"  
					 data-x="40" 
					 data-y="130" 
					 data-speed="450" 
					 data-start="1100" 
					 data-easing="easeOutExpo"  >Wordpress theme</div>
								
				<div class="tp-caption main-text-white lfl"  
					 data-x="0" 
					 data-y="230" 
					 data-speed="450" 
					 data-start="850" 
					 data-easing="easeOutExpo"  >There are many variations of passages of Lorem Ipsum available, <br>
but the some form.</div>
								
				<div class="tp-caption noshadow lfl"  
					 data-x="237" 
					 data-y="320" 
					 data-speed="450" 
					 data-start="1422" 
					 data-easing="easeOutExpo"  ><a href="#" class="button active">Read more</a></div>
								
				<div class="tp-caption lfr"  
					 data-x="679" 
					 data-y="32" 
					 data-speed="450" 
					 data-start="1211" 
					 data-easing="easeOutExpo"  ><img src="http://8theme.com/dev/new/wp-content/uploads/2013/05/imac-1.png" alt="Image 7">div>
								
				<div class="tp-caption lfr"  
					 data-x="805" 
					 data-y="207" 
					 data-speed="450" 
					 data-start="1722" 
					 data-easing="easeOutExpo"  ><img src="http://8theme.com/dev/new/wp-content/uploads/2013/05/macbook.png" alt="Image 8"></div>
								
				<div class="tp-caption lfr"  
					 data-x="628" 
					 data-y="220" 
					 data-speed="450" 
					 data-start="2033" 
					 data-easing="easeOutExpo"  ><img src="http://8theme.com/dev/new/wp-content/uploads/2013/05/ipad-1.png" alt="Image 9"></div>
								
				<div class="tp-caption lfr"  
					 data-x="580" 
					 data-y="315" 
					 data-speed="450" 
					 data-start="2300" 
					 data-easing="easeOutExpo"  ><img src="http://8theme.com/dev/new/wp-content/uploads/2013/05/iphone-1.png" alt="Image 10"></div>
												</li>
									<li data-transition="slidehorizontal" data-slotamount="7" data-masterspeed="300" data-delay="8000" >
						<img src="http://8theme.com/dev/new/wp-content/uploads/2013/05/slider_062.jpg"  alt="slider_062" data-fullwidthcentering="on">
														
				<div class="tp-caption main-caption lft"  
					 data-x="40" 
					 data-y="130" 
					 data-speed="300" 
					 data-start="500" 
					 data-easing="easeOutExpo"  >Wordpress theme</div>
								
				<div class="tp-caption main-text sfl"  
					 data-x="0" 
					 data-y="230" 
					 data-speed="300" 
					 data-start="900" 
					 data-easing="easeOutExpo"  >There are many variations of passages of Lorem Ipsum available, <br>
but the some form.</div>
								
				<div class="tp-caption noshadow lfb"  
					 data-x="237" 
					 data-y="320" 
					 data-speed="450" 
					 data-start="1300" 
					 data-easing="easeOutExpo"  ><a href="#" class="button active">Shop Now</a></div>
												</li>
									<li data-transition="slidehorizontal" data-slotamount="7" data-masterspeed="300" >
						<img src="http://8theme.com/dev/new/wp-content/uploads/2013/05/slider_105.jpg"  alt="slider_105" data-fullwidthcentering="on">
														
				<div class="tp-caption fade"  
					 data-x="420" 
					 data-y="0" 
					 data-speed="300" 
					 data-start="500" 
					 data-easing="easeOutExpo"  ><img src="http://8theme.com/dev/new/wp-content/uploads/2013/05/ipad_21.png" alt="Image 2"></div>
								
				<div class="tp-caption main-caption lft"  
					 data-x="40" 
					 data-y="130" 
					 data-speed="300" 
					 data-start="800" 
					 data-easing="easeOutExpo"  >Mobile Ready</div>
								
				<div class="tp-caption main-text lfl"  
					 data-x="15" 
					 data-y="230" 
					 data-speed="300" 
					 data-start="1100" 
					 data-easing="easeOutExpo"  >There are many variations of passages of Lorem <br>
Ipsum available, but the some form.</div>
								
				<div class="tp-caption noshadow lfb"  
					 data-x="180" 
					 data-y="320" 
					 data-speed="300" 
					 data-start="1400" 
					 data-easing="easeOutExpo"  ><a href="#" class="button active">Shop Now</a></div>
												</li>
									<li data-transition="slidehorizontal" data-slotamount="7" data-masterspeed="300" >
						<img src="http://8theme.com/dev/new/wp-content/uploads/2013/05/slider_071.jpg"  alt="slider_071" data-fullwidthcentering="on">
														
				<div class="tp-caption heading-white lfr"  
					 data-x="72" 
					 data-y="280" 
					 data-speed="700" 
					 data-start="700" 
					 data-easing="easeOutExpo"  >Responsive and flexible<br>
Layout</div>
								
				<div class="tp-caption heading-white lfr"  
					 data-x="400" 
					 data-y="280" 
					 data-speed="700" 
					 data-start="1300" 
					 data-easing="easeOutExpo"  >A lot of useful<br>
shortcodes</div>
								
				<div class="tp-caption heading-white lfr"  
					 data-x="640" 
					 data-y="280" 
					 data-speed="700" 
					 data-start="1900" 
					 data-easing="easeOutExpo"  >Poverfull admin<br>
module</div>
								
				<div class="tp-caption heading-white lfr"  
					 data-x="930" 
					 data-y="280" 
					 data-speed="700" 
					 data-start="2500" 
					 data-easing="easeOutExpo"  >AJAX Catalog <br>
filter</div>
								
				<div class="tp-caption heading-white lfr"  
					 data-x="120" 
					 data-y="130" 
					 data-speed="700" 
					 data-start="700" 
					 data-easing="easeOutExpo"  ><a href="#" class="slide-feature feature-responsive">responsive</a></div>
								
				<div class="tp-caption heading-white lfr"  
					 data-x="410" 
					 data-y="130" 
					 data-speed="700" 
					 data-start="1300" 
					 data-easing="easeOutExpo"  ><a href="#" class="slide-feature feature-shortcodes">shortcodes</a></div>
								
				<div class="tp-caption heading-white lfr"  
					 data-x="660" 
					 data-y="130" 
					 data-speed="700" 
					 data-start="1900" 
					 data-easing="easeOutExpo"  ><a href="#" class="slide-feature feature-admin-panel">admin-panel</a></div>
								
				<div class="tp-caption heading-white lfr"  
					 data-x="925" 
					 data-y="130" 
					 data-speed="700" 
					 data-start="2500" 
					 data-easing="easeOutExpo"  ><a href="#" class="slide-feature feature-ajax">ajax</a></div>
												</li>
									<li data-transition="slidehorizontal" data-slotamount="7" data-masterspeed="300" >
						<img src="http://8theme.com/dev/new/wp-content/uploads/2013/05/slider_131.jpg"  alt="slider_131" data-fullwidthcentering="on">
														
				<div class="tp-caption boxshadow fade"  
					 data-x="640" 
					 data-y="75" 
					 data-speed="300" 
					 data-start="500" 
					 data-easing="easeOutExpo"  ><iframe src='http://www.youtube.com/embed/NtbU54uZlPg?hd=1&amp;wmode=opaque&amp;controls=1&amp;showinfo=0;rel=0' width='480' height='320' style='width:480px;height:320px;'></iframe></div>
								
				<div class="tp-caption main-caption lfb"  
					 data-x="40" 
					 data-y="130" 
					 data-speed="300" 
					 data-start="800" 
					 data-easing="easeOutExpo"  >Wordpress theme</div>
								
				<div class="tp-caption main-text lfb"  
					 data-x="0" 
					 data-y="230" 
					 data-speed="300" 
					 data-start="1100" 
					 data-easing="easeOutExpo"  >There are many variations of passages of Lorem Ipsum available, <br>
but the some form.</div>
								
				<div class="tp-caption noshadow lfb"  
					 data-x="237" 
					 data-y="320" 
					 data-speed="300" 
					 data-start="1400" 
					 data-easing="easeOutExpo"  ><a href="#" class="button active">Shop Now</a></div>
												</li>
								</ul>
									<div class="tp-bannertimer tp-bottom"></div>					</div>
				</div>				
							
			<script type="text/javascript">

				var tpj=jQuery;
				
									tpj.noConflict();
								
				var revapi2;
				
				tpj(document).ready(function() {
				
				if (tpj.fn.cssOriginal != undefined)
					tpj.fn.css = tpj.fn.cssOriginal;
				
				if(tpj('#rev_slider_2_1').revolution == undefined)
					revslider_showDoubleJqueryError('#rev_slider_2_1');
				else
				   revapi2 = tpj('#rev_slider_2_1').show().revolution(
					{
						delay:9000,
						startwidth:1200,
						startheight:480,
						hideThumbs:0,
						
						thumbWidth:100,
						thumbHeight:50,
						thumbAmount:5,
						
						navigationType:"none",
						navigationArrows:"solo",
						navigationStyle:"round",
						
						touchenabled:"on",
						onHoverStop:"on",
						
						navigationHAlign:"center",
						navigationVAlign:"bottom",
						navigationHOffset:0,
						navigationVOffset:20,

						soloArrowLeftHalign:"left",
						soloArrowLeftValign:"center",
						soloArrowLeftHOffset:0,
						soloArrowLeftVOffset:0,

						soloArrowRightHalign:"right",
						soloArrowRightValign:"center",
						soloArrowRightHOffset:0,
						soloArrowRightVOffset:0,
								
						shadow:0,
						fullWidth:"on",

						stopLoop:"off",
						stopAfterLoops:-1,
						stopAtSlide:-1,

						shuffle:"off",
						
						hideSliderAtLimit:0,
						hideCaptionAtLimit:0,
						hideAllCaptionAtLilmit:0,
						startWithSlide:0	
					});
				
				});	//ready
				
			</script>
			
							<!-- END REVOLUTION SLIDER -->
				</div>
