<?php 
$_menu = $this->renderCategoriesMenuHtml(0,'level-top');
$themeOptions = $this->helper('idstore');
$menuHelper = $this->helper('etheme_menu');
$baseUrl = $this->getBaseUrl();
$currentUrl = Mage::helper('core/url')->getCurrentUrl();

?>


<div class="menu visible-desktop">
    <ul id="nav" class="menutype<?php echo $menuHelper->menuType(); ?>">
        <?php if ($home_link = $menuHelper->getHomeLink()) : ?>
        <li class="level0 level-top nav-0 <?php if ($baseUrl == $currentUrl): ?>active<?php endif?>">
            <a href="<?php echo $baseUrl ?>"><?php echo $home_link ?></a>
        </li>
        <?php endif ?>
        <?php echo $_menu ?>
        <?php if ($addLink = $menuHelper->additionalLink()): ?>
        <li class="level0 additional level-top">
            <a href="<?php echo $menuHelper->additionalLinkUrl() ?>"><?php echo $addLink ?></a>
        </li>
        <?php endif ?>
    </ul>
</div>
<span class="et-menu-title"><i class="icon-reorder"></i></span>