<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
        
    $themeOptions = $this->helper('idstore');
    $enableAjax = $themeOptions->ajaxIsEnabled();
    $cols = $themeOptions->gridColumnCount();
    $template = $this->getLayout()->getBlock('root')->getTemplate();
    
    $catHelper = $this->helper('idstore/category');
    $catHelper->setOptions($cols, $template);
    $isHoverswapEnabled = $themeOptions->useHoverSwap();
    $imgW1 = $catHelper->getImgWidth();
    $imgH1 = $catHelper->getImgHeight();
    $span_class = $catHelper->getSpanClass();
    $imgW = 540;
    $imgH = 740;
    
?>

<?php if (!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if ($this->getMode() != 'grid'): ?>
    <?php $_iterator = 0; ?>
    <div class="products_list">
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product):?>
        <li class="item<?php if ( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
            <?php echo $this->getLayout()->createBlock('idstore/product_ribbons')->setTemplate('catalog/product/view/ribbons.phtml')->setData('product', $_product)->toHtml(); ?>
            <?php if ($isHoverswapEnabled): ?>
            <div class="img-wrapper"><?php echo $this->getLayout()->createBlock('idstore/product_hoverswap')->setTemplate('catalog/product/view/hoverswap.phtml')->setData('product', $_product)->setData('width', $imgW)->setData('height', $imgH)->toHtml(); ?></div>
            <?php endif ?>
            <div class="img-wrapper<?php if ($isHoverswapEnabled) echo ' hideableHover' ?>"><img class="product_image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(true)->resize($imgW, $imgH) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
            </div>
            </a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>

<!-- Cabooza.com CB-6-PHTML -->

<h6><?php echo $_product->getShortDescription(); ?></h6>

                    <?php if ($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>

                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <ul class="add-to-links<?php if (!$themeOptions->useAddtoButtons()) echo ' hidden'?>">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if ($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
	            <div class="addtocont">
		            <?php echo $this->getPriceHtml($_product, true) ?>
		            <?php if ($_product->isSaleable()): ?>
		                <?php if ( !($_product->getTypeInstance(true)->hasOptions($_product) || $_product->isGrouped()) ): ?>
		                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="eightTheme.ajaxAddProduct('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
		                <?php else: ?>
		                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="eightTheme.ajaxShowOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
		                <a href='<?php echo $this->getUrl('e_ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style="display: none;" ><?php echo $this->__('Add to Cart') ?></a>
		                <?php endif ?>
		            <?php else: ?>
		                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
		            <?php endif; ?>
	            </div>
            </div>
        <div id="productimgover<?php echo $_product->getId()?>" style="display: none;"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(64); ?>" width="64" height="64" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></div>
        <div id='productname<?php echo $_product->getId()?>' style='display:none'><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></div>
        </li>
    <?php endforeach; ?>
    </ol>
    </div>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>


    <?php else: ?>
	
	    <?php // Grid Mode ?>
	
	    <?php $_collectionSize = $_productCollection->count() ?>
	    <?php $_columnCount = $this->getColumnCount(); ?>
	    
	    <div class="products_grid row rows-count<?php echo $_columnCount ?>">
	    
	    	<?php $i=0; foreach ($_productCollection as $_product): ?>
	    	
	            <div class="product-grid  <?php echo $span_class ?>	<?php if (($i-1)%$_columnCount==0): ?> first<?php elseif ($i%$_columnCount==0): ?> last<?php endif; ?>">
	            

                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
                    	<?php echo $this->getLayout()->createBlock('idstore/product_ribbons')->setTemplate('catalog/product/view/ribbons.phtml')->setData('product', $_product)->toHtml(); ?>
                        <?php if ($isHoverswapEnabled): ?>
                        <div class="img-wrapper"><?php echo $this->getLayout()->createBlock('idstore/product_hoverswap')->setTemplate('catalog/product/view/hoverswap.phtml')->setData('product', $_product)->setData('width', $imgW)->setData('height', $imgH)->toHtml(); ?></div>
                        <?php endif ?>
                        <div class="img-wrapper<?php if ($isHoverswapEnabled) echo ' hideableHover' ?>"><img class="product_image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(true)->resize($imgW, $imgH) ?>" width="<?php echo $imgW ?>" height="<?php echo $imgH ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                        </div>
                    </a>
		            <div class="product-information">
		            
			            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>


<!-- Cabooza.com CB-6-PHTML -->			            
<h6><?php echo $_product->getShortDescription(); ?></h6>

			            <?php if ($_product->getRatingSummary()): ?>
			            	<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
			            <?php endif; ?>
			            
			            <div id="productname<?php echo $_product->getId() ?>" style="display:none"><?php echo $this->stripTags($_product->getName(), null, true) ?></div>
			            
			            <?php echo $this->getPriceHtml($_product, true) ?>
			            
		                <ul class="add-to-links<?php if (!$themeOptions->useAddtoButtons()) echo ' hidden'?>">
		                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
		                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
		                    <?php endif; ?>
		                    <?php if ($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
		                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
		                    <?php endif; ?>
		                </ul>
		                <div class="clear"></div>
		            </div>
					
					<?php
					$idthisproduct = $_product->getId();
					?>
					<div class="prodid"><?php echo $idthisproduct;?></div>
					<?php
					$numberincart=0;
					$cart = Mage::getModel('checkout/cart')->getQuote();
					foreach ($cart->getAllItems() as $item) {
						$idcartproduct = $item->getProduct()->getId();
						if($idcartproduct == $idthisproduct){
							$numberincart = $item->getQty();
						}
					}
					
					?>
					<div id="<?php echo 'adt'.$idthisproduct;?>" class="adt" style="display:none;">
						<div class="qty"></div>
						<button id="<?php echo 'qtyr'.$idthisproduct; $_SESSION['qty'.$idthisproduct] = 'eightTheme.ajaxAddProduct(\''.$this->getAddToCartUrl($_product).'\',\''.$_product->getId().'\');addp('.$idthisproduct.');';$_SESSION['qtyr'.$idthisproduct] = 'eightTheme.ajaxRemoveOne(\''.$this->getAddToCartUrl($_product).'\',\''.$_product->getId().'\');remp('.$idthisproduct.');';?>" onclick="eightTheme.ajaxRemoveOne('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>');remp(<?php echo $idthisproduct;?>);" class="del"></button>
						<button id="<?php echo 'qtyr'.$idthisproduct; $_SESSION['qty'.$idthisproduct] = 'eightTheme.ajaxAddProduct(\''.Mage::helper('checkout/cart')->getAddUrl($_product).'\',\''.$_product->getId().'\');addp('.$idthisproduct.');';$_SESSION['qtyr'.$idthisproduct] = 'eightTheme.ajaxRemoveOne(\''.Mage::helper('checkout/cart')->getAddUrl($_product).'\',\''.$_product->getId().'\');remp('.$idthisproduct.');';?>" onclick="eightTheme.ajaxAddProduct('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>','<?php echo $_product->getId()?>');addp(<?php echo $idthisproduct;?>);" class="add"></button>
					</div> 
					
					<div class="actions btn-cont" onclick="eightTheme.ajaxAddProduct('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>');addp(<?php echo $idthisproduct;?>);">  
						<?php if ($_product->isSaleable()): ?>
							<?php if ( !($_product->getTypeInstance(true)->hasOptions($_product) || $_product->isGrouped()) ): ?>
							
							<?php else: ?>
							<button type="button" title="<?php echo $this->__('+') ?>" class="button btn-cart" onclick="eightTheme.ajaxShowOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('+') ?></span></span></button>
							<a href='<?php echo $this->getUrl('e_ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style="display: none;" ><?php echo $this->__('+') ?></a>
							<?php endif ?>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
					</div>
					<?php
						if($numberincart > 0){
							?>
							<script>
								var element="<?php echo '#adt'.$idthisproduct; ?>";
								jQuery(element).show();
								jQuery(element).next().css('display','block');
								jQuery(element).find('.qty').text(<?php echo $numberincart;?>);
							</script>
							<?php
						}
					?>
		            <div id="productimgover<?php echo $_product->getId()?>" style="display: none;"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(75); ?>" width="64" height="64" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></div>
		            <div id='productname<?php echo $_product->getId()?>' style='display:none'><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></div>
		            
	            </div>
	            
	        <?php endforeach ?>
	        
        </div>
        
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
	        
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
<script>

</script>